splash = false

wallpaper {
	monitor = eDP-2
	path = ~/pictures/wallpaper/dracula/dracula(11).png
	fit_mode = cover

}
wallpaper {
	monitor = HDMI-A-1
	path = ~/pictures/wallpaper/dracula/dracula(11).png
	fit_mode = cover

}
