general {
    hide_cursor = true
}

background {
    monitor =
    path = @WALLPAPER@
    color = @LOCK_BACKGROUND_RGBA@
    blur_passes = 0
    blur_size = 7
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

input-field {
    monitor =
    size = 200, 50
    outline_thickness = 3
    dots_size = 0.33
    dots_spacing = 0.15
    dots_center = true
    dots_rounding = -1

    outer_color = @LOCK_ACCENT_RGB@
    inner_color = @LOCK_INNER_RGB@
    font_color = @LOCK_FONT_RGB@

    fade_on_empty = true
    fade_timeout = 1000
    placeholder_text = <i>Input Password...</i>
    hide_input = false
    rounding = -1

    check_color = @LOCK_CHECK_RGB@
    fail_color = @LOCK_FAIL_RGB@
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>

    capslock_color = -1
    numlock_color = -1
    bothlock_color = -1
    invert_numlock = false
    swap_font_color = false

    position = 0, -50
    halign = center
    valign = center
}

image {
    monitor =
    path = /home/w0lf/.cache/hyprlock/ascii-clock.png
    size = 125
    rounding = 0
    border_size = 0
    rotate = 0
    reload_time = 1
    reload_cmd = /home/w0lf/.config/hypr/scripts/render_hyprlock_clock.py

    position = 0, 150
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] date +"%A %B %d, %Y"
    text_align = center
    color = @LOCK_DATE_RGBA@
    font_size = 12
    font_family = Monospace
    rotate = 0

    position = 0, 65
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:30000] /home/w0lf/.config/hypr/scripts/lock_status.sh
    text_align = center
    color = @LOCK_STATUS_RGBA@
    font_size = 10
    font_family = Monospace
    rotate = 0

    position = 0, 38
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:43200000] /home/w0lf/.config/hypr/scripts/greeting.sh
    text_align = center
    color = @LOCK_FOREGROUND_RGBA@
    font_size = 20
    font_family = Monospace
    rotate = 0

    position = 0, 10
    halign = center
    valign = center
}
