-- Generated by bin/hypr-theme. Edit themes/<name>/theme.json, not this file.
-- Active theme: dracula (Dracula)

hl.config({
    general = {
        col = {
            active_border = { colors = { "rgba(bd93f9ff)", "rgba(ff79c6ff)" }, angle = 45 },
            inactive_border = "rgba(595959aa)",
        },
    },
    decoration = {
        rounding = 10,
    },
})
